language: objective-c

before_install:
    - gem install cocoapods
    - brew update
    - brew uninstall xctool && brew install xctool
    - cd AeroGear-iOS-Integration

script:
    - xctool -workspace AeroGear-iOS-Integration.xcworkspace -scheme AeroGear-iOS-IntegrationTests -sdk iphonesimulator -configuration Release test -freshSimulator -freshInstall

branches:
  only:
    - master
