xcodeproj 'AeroGear-iOS-Integration.xcodeproj'

platform :ios

pod 'AeroGear', :git => 'https://github.com/aerogear/aerogear-ios.git', :branch => 'AEROGEAR-855'

target 'AeroGear-iOS-IntegrationTests', :exclusive => true do
	pod 'Kiwi'
end
